language: node_js

services:
  - docker

before_install:
  - docker build -t sulhadin/react-pokemon .
  - docker run -d -p 127.0.0.1:80:4567 sulhadin/react-pokemon /bin/sh -c "cd /root/react-pokemon; bundle exec foreman start;"
  - docker ps -a
  - docker run sulhadin/react-pokemon /bin/sh -c "cd /root/react-pokemon; bundle exec rake test"

script:
  - bundle exec rake test
